name: 'Shortcut Ticket Check'
description: 'Check PR Comments for Shortcut Bot Comment'
inputs:
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'
